version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    labels:
      - "deps"
      - "frontend"
    commit-message:
      prefix: "deps(npm)"
    versioning-strategy: increase

  - package-ecosystem: "pip"
    directory: "/backend"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    labels:
      - "deps"
      - "backend"
    commit-message:
      prefix: "deps(pip)"
    insecure-external-code-execution: deny


